## DATABASE

## Connection
default_connection: mysql

## MySQL
database: thunder
host: localhost
username: homestead
password: secret
charset: utf8
collation: utf8_unicode_ci
lazy: true

## RESPONSE FORMATER
response_format: json